# Generated by Django 2.1.3 on 2018-11-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_auto_20181129_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationUpdateScriptPathAfter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='复制到远程服务器运行脚本的位置'),
        ),
    ]
