# Generated by Django 2.1.3 on 2018-12-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_auto_20181130_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ApplicationBranch',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='拉取的仓库的分支'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationUpdateScriptPath',
            field=models.CharField(max_length=200, verbose_name='运行devops服务器上的拉取仓库的脚本位置'),
        ),
    ]
