# Generated by Django 2.1.3 on 2018-12-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0011_applicationlogs_logsfilename'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteServerService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=100, verbose_name='远程服务的名字')),
                ('ServicePort', models.CharField(max_length=20, verbose_name='该服务启动的端口')),
                ('ServiceAtServer', models.ForeignKey(on_delete='服务在哪台服务器上', to='infrastructure.Server')),
            ],
            options={
                'verbose_name_plural': '所有远程服务器上的服务',
                'ordering': ['ServiceName'],
            },
        ),
    ]
