# Generated by Django 2.1.3 on 2019-01-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0013_updatelogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PathOfGoTask', models.CharField(max_length=200, verbose_name='go-task的路径')),
                ('TaskInServer', models.ForeignKey(on_delete='go-task所在的服务器', to='infrastructure.Server')),
            ],
            options={
                'verbose_name_plural': 'GOtask配置表',
                'ordering': ['TaskInServer'],
            },
        ),
    ]
