# Generated by Django 2.1.3 on 2019-01-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0014_gotask'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatelogs',
            name='UpdateTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新task的时间'),
        ),
    ]
