# Generated by Django 2.1.3 on 2019-01-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0016_auto_20190130_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatelogs',
            name='UpdateTime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新task的时间'),
        ),
    ]
