# Generated by Django 2.1.3 on 2019-03-05 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0017_auto_20190130_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_level', models.CharField(default='测试', max_length=50, verbose_name='应用的级别（生产还是测试）')),
            ],
            options={
                'verbose_name_plural': '应用级别',
                'ordering': ['application_level'],
            },
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleType', models.CharField(default='develop', max_length=50, verbose_name='权限角色')),
            ],
            options={
                'verbose_name_plural': '权限角色',
                'ordering': ['RoleType'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='ApplicationLevel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.ApplicationLevel', verbose_name='应用的级别'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.RoleType', verbose_name='角色类型'),
        ),
    ]
