# Generated by Django 2.1.3 on 2019-03-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0018_auto_20190305_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatelogs',
            name='UpdateUser',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人'),
        ),
    ]
