# Generated by Django 2.1.3 on 2019-04-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0019_updatelogs_updateuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoTaskIP', models.GenericIPAddressField(verbose_name='gotask所在的ip地址')),
                ('GoTaskStatus', models.CharField(max_length=20, verbose_name='Gotask状态')),
            ],
            options={
                'verbose_name_plural': 'GOtask状态',
                'ordering': ['GoTaskIP'],
            },
        ),
    ]
